# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Xwkjf-edzvYPOKwc9ST6C9e2xjTijGA

Meu primeiro programa em Python
print("meu primeiro programa em python")

Vou fazer um calculo simples
(5+8+9)*5
"""

print("meu primeiro programa em python")

"""Vou fazer um calculo simples"""

(5+8+9)*5

resultado = (5+8+9)*5
print(resultado)

"""Programa que solicita o nome e idade da pessoa"""

tefi = input("seu nome: ")
idade = input("sua idade: ")
print("seu nome é", tefi, "e sua idade é", idade, "anos")
if idade >= 18:
    print("pode dirigir")
else:
    print("nao pode dirigir")

"""calcular peso"""

peso = input("seu peso: ")
print("seu peso é", peso, "kg")
resultado = float(peso) / 2

"""Multiplicação de preço"""

preco_compra = 49.90
int qauntidade = 3
preco_total = preco_compra * qauntidade
print(preco_total)

"""Formatar texto"""

print('o preço total foi: R$ {:.2f}'.format(preco_total))
print(f'O valor total foi: R$ {preco_total:.2f}')

"""Aplicando condição if/else"""

idade = int(input('digite sua idade: '))
if idade >= 18:
    print("maior de idade")
else:
    print("menor")

"""Criar lista

"""

frutas = ["maçâ","banana", "morango","livia","edson"]
for isabella in frutas:
  print(f"eu gosto de: {isabella}")

"""Análise de dados pandas e grafico"""

import pandas as pd
import matplotlib.pyplot as plt

"""Conjunto de dados"""

dados = {
    "mes": ["Jan", "Fev", "Mar", "Abr"],
    "vendas": [1500, 2300, 1800, 3100]
}

"""Transformando a tabela (matriz) dataframe O objeto do pandas recebe a matriz de dados (dataframe)"""

df =pd.DataFrame(dados)

"""Gerar o gráfico com os dados"""

plt.plot (df["mes"], df["vendas"])
plt.show()
#

plt.plot(df["mes"], df["vendas"], marker="o",color='green')
plt.title("Evolução das Vendas por mensais, do primeiro quadrimestre")
plt.xlabel("Mês")
plt.ylabel("Vendas em R$")
plt.show()
#

plt.style.use('dark_background')

plt.plot(
    df["mes"],
    df["vendas"],
    marker="o",
    markersize=10,
    color='#FF0000',
    linewidth=3,
    markeredgecolor='#0055FF',
    markeredgewidth=3
)
plt.title("🕷️ EVOLUÇÃO DAS VENDAS - MODO ARANHA 🕷️", color='#FF0000', fontsize=14, fontweight='bold')
plt.xlabel("Mês", color='#0099FF', fontsize=11, fontweight='bold')
plt.ylabel("Vendas em R$", color='#0099FF', fontsize=11, fontweight='bold')
plt.grid(color='#FF0000', linestyle='--', alpha=0.3)

plt.show()

"""Calculando o consumo do veiculo"""

tefi = float(input("Digite a capacidade do tanque: "))
quilometros_litro = float(input('quantos km o carro faz? '))
estefani = tefi * quilometros_litro
print(f'A autonomia do carro é: {estefani:.2f}km')

"""Utilizando if/elif/else
Classificação de idades
Forneça as idades e mostre sua categoria
#-----
menor q 12 criança
12 -17 anos - adolescente
18 - 59 adulto
60 + idoso
"""

teff = int(input("digite sua idade: "))
if teff < 0:
    print("idade invalida")
elif teff < 12:
    print("criança")
elif teff <= 17:
    print("adolescente")
elif teff <= 59:
    print("adulto")
else:
    print("idoso")